version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - run:
          name: Run Yarn
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
